// src/controllers/reportController.js
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const { v4: uuidv4 } = require('uuid');
const { pool } = require('../config/db');

const REPORTS_DIR = path.join(__dirname, '..', '..', 'generated_reports');
if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });

async function gatherInvestigationData(investigationId) {
  const [[investigation]] = await pool.query('SELECT * FROM investigations WHERE id = ?', [investigationId]);
  const [wallets] = await pool.query('SELECT * FROM wallets WHERE investigation_id = ?', [investigationId]);
  const [transactions] = await pool.query('SELECT * FROM transactions WHERE investigation_id = ? ORDER BY tx_timestamp', [investigationId]);
  const [riskRows] = await pool.query(
    `SELECT r.*, w.address FROM risk_analysis r JOIN wallets w ON w.id = r.wallet_id WHERE r.investigation_id = ?`,
    [investigationId]
  );
  return { investigation, wallets, transactions, riskRows };
}

function generatePdfReport(filePath, { investigation, wallets, transactions, riskRows }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(20).text('CryptoTrace AI — Investigation Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Investigation: ${investigation?.title || 'N/A'}`);
    doc.text(`Case type: ${investigation?.case_type || 'N/A'}`);
    doc.text(`Status: ${investigation?.status || 'N/A'}`);
    doc.text(`Generated: ${new Date().toISOString()}`);
    doc.moveDown();

    doc.fontSize(15).text('Wallets Analyzed', { underline: true });
    doc.moveDown(0.5);
    wallets.forEach(w => {
      doc.fontSize(10).text(`${w.address} (${w.chain}) — balance: ${w.balance} (~$${w.balance_usd}) — tx count: ${w.total_tx_count}`);
    });
    doc.moveDown();

    doc.fontSize(15).text('Risk Assessment', { underline: true });
    doc.moveDown(0.5);
    riskRows.forEach(r => {
      doc.fontSize(10).text(`${r.address} — risk: ${r.risk_level.toUpperCase()} (${r.risk_score}/100)`);
      if (r.probable_end_receiver_address) {
        doc.fontSize(9).fillColor('gray').text(`   Probable end receiver: ${r.probable_end_receiver_address} (confidence ${r.end_receiver_confidence}%)`);
        doc.fillColor('black');
      }
    });
    doc.moveDown();

    doc.fontSize(15).text('Transaction Timeline (sample)', { underline: true });
    doc.moveDown(0.5);
    transactions.slice(0, 50).forEach(t => {
      doc.fontSize(9).text(`${t.tx_timestamp} — ${t.from_address} → ${t.to_address} — ${t.amount} ${t.chain.toUpperCase()}`);
    });

    doc.moveDown();
    doc.fontSize(8).fillColor('gray').text(
      'Disclaimer: Risk levels and end-receiver predictions are generated by heuristic rules for demonstration purposes and have not been validated against ground-truth forensic data. Verify all findings manually before relying on them.',
      { align: 'left' }
    );

    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

async function generateExcelReport(filePath, { investigation, wallets, transactions, riskRows }) {
  const workbook = new ExcelJS.Workbook();

  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.addRow(['Investigation', investigation?.title || 'N/A']);
  summarySheet.addRow(['Case Type', investigation?.case_type || 'N/A']);
  summarySheet.addRow(['Status', investigation?.status || 'N/A']);
  summarySheet.addRow(['Generated', new Date().toISOString()]);

  const walletSheet = workbook.addWorksheet('Wallets');
  walletSheet.addRow(['Address', 'Chain', 'Balance', 'Balance USD', 'Total Tx Count', 'First Tx', 'Last Tx']);
  wallets.forEach(w => walletSheet.addRow([w.address, w.chain, w.balance, w.balance_usd, w.total_tx_count, w.first_tx_at, w.last_tx_at]));

  const riskSheet = workbook.addWorksheet('Risk Analysis');
  riskSheet.addRow(['Address', 'Risk Level', 'Risk Score', 'Probable End Receiver', 'Confidence %']);
  riskRows.forEach(r => riskSheet.addRow([r.address, r.risk_level, r.risk_score, r.probable_end_receiver_address, r.end_receiver_confidence]));

  const txSheet = workbook.addWorksheet('Transactions');
  txSheet.addRow(['Tx Hash', 'Chain', 'From', 'To', 'Amount', 'Timestamp']);
  transactions.forEach(t => txSheet.addRow([t.tx_hash, t.chain, t.from_address, t.to_address, t.amount, t.tx_timestamp]));

  await workbook.xlsx.writeFile(filePath);
}

async function generateReport(req, res, next) {
  try {
    const { investigationId, reportType, format } = req.body;
    const data = await gatherInvestigationData(investigationId);

    if (!data.investigation) {
      return res.status(404).json({ success: false, message: 'Investigation not found' });
    }

    const fileName = `report_${investigationId}_${Date.now()}.${format}`;
    const filePath = path.join(REPORTS_DIR, fileName);

    if (format === 'pdf') {
      await generatePdfReport(filePath, data);
    } else if (format === 'xlsx') {
      await generateExcelReport(filePath, data);
    } else {
      return res.status(422).json({ success: false, message: 'format must be "pdf" or "xlsx"' });
    }

    const reportUuid = uuidv4();
    await pool.query(
      `INSERT INTO reports (uuid, investigation_id, generated_by, report_type, file_format, file_path)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [reportUuid, investigationId, req.user.id, reportType, format, fileName]
    );

    res.json({ success: true, data: { downloadUrl: `/api/reports/download/${fileName}`, fileName } });
  } catch (err) {
    next(err);
  }
}

function downloadReport(req, res) {
  const filePath = path.join(REPORTS_DIR, req.params.fileName);
  if (!fs.existsSync(filePath)) {
    return res.status(404).json({ success: false, message: 'Report file not found' });
  }
  res.download(filePath);
}

module.exports = { generateReport, downloadReport };
